"""Claude-driven conflict resolution: render the prompt, run the agent, verify the result."""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from types import SimpleNamespace
from typing import TYPE_CHECKING, Literal

from rich.markup import escape

from releasy.termlog import console

from releasy.config import AIApiConfig, AICodexConfig, Config, PortMode
from releasy.git_ops import (
    is_operation_in_progress,
    run_git,
)
from releasy.github_ops import (
    PRInfo,
    add_issue_comment,
    add_label_to_pr,
    get_origin_repo_slug,
    parse_pr_url,
)

if TYPE_CHECKING:
    from releasy.api_agent import ApiAgentSpec


OperationKind = Literal["cherry-pick", "merge"]


@dataclass
class AIResolveContext:
    port_branch: str
    base_branch: str
    # cherry-pick: the PR being ported; merge: the source PR the rebase branch ports.
    source_pr: PRInfo
    conflict_files: list[str] = field(default_factory=list)
    # Port branch tip before the conflicting operation; reset target on failure.
    start_sha: str | None = None
    operation: OperationKind = "cherry-pick"
    rebase_pr_url: str | None = None  # merge only
    # ``ai_context:`` note from the session file; empty ⇒ no prompt section.
    user_context: str = ""
    # Cherry-pick already committed with conflict markers; Claude adds a resolution commit on top.
    split_mode: bool = False
    pre_resolve_sha: str | None = None  # HEAD after the "with conflicts" commit
    mode: PortMode = "forward_port"
    # Resolve + commit only; RelEasy builds afterwards via ``build_verify``.
    skip_build: bool = False


@dataclass
class AIResolveResult:
    success: bool
    iterations: int | None = None
    error: str | None = None
    timed_out: bool = False
    new_head: str | None = None
    # Summed across every attempt; None when no result event reported a cost.
    cost_usd: float | None = None
    # Set from a ``MISSING_PREREQS:`` / ``REASON:`` report (always with success=False).
    missing_prereq_prs: list[str] = field(default_factory=list)
    missing_prereq_note: str | None = None
    # Died before the model could work (API error, unusable backend, missing
    # prompt); callers must not spend a retry on it. Timeouts are not this.
    api_aborted: bool = False
    # Downgraded postcondition failures (success=True); callers flag them on the PR.
    warnings: list[str] = field(default_factory=list)


# Claude Code's Bash matcher refuses compound commands and build output is too
# large for one tool result, so the build runs via a wrapper that tees to a log.
_BUILD_DIR = ".releasy"
_BUILD_SCRIPT = f"{_BUILD_DIR}/build.sh"


def build_log_path(branch: str) -> str:
    """Per-branch build-log path relative to the repo root (a failed branch's log must survive)."""
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", branch).strip("-")
    return f"{_BUILD_DIR}/build-{slug}.log" if slug else f"{_BUILD_DIR}/build.log"


def _write_build_script(
    repo_path: Path, build_command: str, log_path: str,
) -> None:
    target = repo_path / _BUILD_SCRIPT
    target.parent.mkdir(parents=True, exist_ok=True)
    body = build_command.rstrip() + "\n"
    # Ported commits can advance submodule pointers.
    script = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by RelEasy. Do not edit by hand — regenerated\n"
        "# on every AI-resolve invocation from ai_resolve.build_command.\n"
        "set -euo pipefail\n"
        "cd \"$(git rev-parse --show-toplevel)\"\n"
        f"mkdir -p {_BUILD_DIR}\n"
        f"exec > >(tee {log_path}) 2>&1\n"
        "echo \"[releasy] build started at $(date -u +%FT%TZ)\"\n"
        "echo \"[releasy] git submodule update --init --recursive\"\n"
        "git submodule update --init --recursive --jobs 8\n"
        "(\n"
        f"{body}"
        ")\n"
        "echo \"[releasy] build finished at $(date -u +%FT%TZ)\"\n"
    )
    target.write_text(script, encoding="utf-8")
    target.chmod(0o755)

    gitignore = repo_path / _BUILD_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n", encoding="utf-8")


def _prompt_path(config: Config, raw: str) -> Path:
    """``raw`` when absolute; else under ``config.repo_dir``, falling back to the bundled copy."""
    p = Path(raw)
    if p.is_absolute():
        return p
    local = (config.repo_dir / p).resolve()
    bundled = Path(__file__).parent / p
    return bundled if not local.exists() and bundled.exists() else local


def _fill_placeholders(template: str, placeholders: dict[str, str]) -> str:
    """Substitute ``{ident}`` placeholders; unknown ones are left verbatim."""
    def _replace(match: re.Match[str]) -> str:
        return placeholders.get(match.group(1), match.group(0))

    return re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", _replace, template)


def _prompt_file_key(ctx: AIResolveContext) -> str:
    """``config.ai_resolve`` attribute naming the prompt template for ``ctx``."""
    if ctx.operation == "merge":
        return "merge_prompt_file"
    if ctx.skip_build:
        return "resolve_only_prompt_file"
    if ctx.split_mode:
        return "split_prompt_file"
    return "prompt_file"


def _render_prompt(config: Config, repo_path: Path, ctx: AIResolveContext) -> str:
    key = _prompt_file_key(ctx)
    prompt_path = _prompt_path(config, getattr(config.ai_resolve, key))

    if not prompt_path.exists():
        raise FileNotFoundError(
            f"AI prompt template not found: {prompt_path}. "
            f"Set ai_resolve.{key} in config."
        )

    template = prompt_path.read_text(encoding="utf-8")

    repo_slug = get_origin_repo_slug(config) or "<unknown>"

    conflict_files_md = "\n".join(f"- `{f}`" for f in ctx.conflict_files) or "- (none)"

    body = (ctx.source_pr.body or "").strip()
    if not body:
        body = "_(empty)_"
    elif len(body) > 4000:
        body = body[:4000] + "\n\n_(truncated)_"

    source_pr_merge_sha = (
        ctx.source_pr.merge_commit_sha or ctx.source_pr.head_sha or ""
    )

    origin_remote_name = config.origin.remote_name
    # Prereq history search branch; not target_branch, which is where the prereq is missing.
    origin_branch_default = "master"

    if config.upstream is not None:
        upstream_remote_name = config.upstream.remote_name
        upstream_branch = config.upstream.branch
        upstream_fetch_section = (
            "Also search the upstream remote (fetch it first):\n\n"
            "```bash\n"
            f"git fetch {upstream_remote_name} {upstream_branch} --depth=500\n"
            f"git log -S '<identifier>' --oneline {upstream_remote_name}/"
            f"{upstream_branch} -- <file>\n"
            "```\n"
        )
    else:
        upstream_remote_name = ""
        upstream_branch = ""
        upstream_fetch_section = (
            "_(no upstream remote is configured; only the origin history "
            "above is searched)_\n"
        )

    # Trailing newline: a following `---` would make the last line a setext heading.
    user_context_text = (ctx.user_context or "").strip()
    if user_context_text:
        user_context_section = (
            "\n## User-supplied context (from session.yaml)\n\n"
            "> The operator attached this note to this PR / group when "
            "configuring the run. Treat it as authoritative guidance from "
            "the human driving the port — but it does NOT override the "
            "diff-fidelity rule below: the source PR's diff is still the "
            "only authoritative list of what the port wants to add.\n\n"
            f"{user_context_text}\n"
        )
    else:
        user_context_section = ""

    placeholders = {
        "repo_slug": repo_slug,
        "cwd": str(repo_path),
        "port_branch": ctx.port_branch,
        "base_branch": ctx.base_branch,
        "source_pr_url": ctx.source_pr.url,
        "source_pr_title": ctx.source_pr.title,
        "source_pr_number": str(ctx.source_pr.number),
        "source_pr_body": body,
        "source_pr_merge_sha": source_pr_merge_sha,
        "conflict_files": conflict_files_md,
        "build_command": config.ai_resolve.build_command,
        "build_script": _BUILD_SCRIPT,
        "build_log": build_log_path(ctx.port_branch),
        "max_iterations": str(config.ai_resolve.max_iterations),
        "label": config.ai_resolve.label,
        "rebase_pr_url": ctx.rebase_pr_url or "",
        "origin_remote_name": origin_remote_name,
        "origin_branch": origin_branch_default,
        "upstream_remote_name": upstream_remote_name,
        "upstream_branch": upstream_branch,
        "upstream_fetch_section": upstream_fetch_section,
        "user_context_section": user_context_section,
        "pre_resolve_sha": ctx.pre_resolve_sha or "",
        "port_direction": ctx.mode,
        "source_pr_labels": ", ".join(
            l for l in (ctx.source_pr.labels or []) if l
        ),
    }

    return _fill_placeholders(template, placeholders)


def _model_effort_args(config: Config) -> list[str]:
    args: list[str] = []
    if config.ai_model:
        args += ["--model", config.ai_model]
    if config.ai_effort:
        args += ["--effort", config.ai_effort]
    return args


# Larger prompts go via stdin: one argv string is capped at 128 KiB (Linux MAX_ARG_STRLEN).
_PROMPT_ARG_MAX_BYTES = 96 * 1024


def _build_claude_argv(
    config: Config, allowed_tools: list[str] | None = None,
) -> list[str]:
    """Print-mode argv without the prompt (``codex exec`` argv under ``ai_backend: codex``)."""
    tools = allowed_tools if allowed_tools is not None else config.ai_resolve.allowed_tools
    if _codex_backend_selected(config):
        return _build_codex_argv(config, tools)
    cmd = [
        config.ai_resolve.command,
        "-p",
        "--output-format", "stream-json",
        "--verbose",
    ]
    if tools:
        cmd += ["--allowedTools", ",".join(tools)]
    cmd += _model_effort_args(config)
    cmd += list(config.ai_resolve.extra_args)
    return cmd


def _argv_with_inline_prompt(base_argv: list[str], prompt: str) -> list[str]:
    """Insert ``prompt`` right after ``-p`` / ``exec`` (small-prompt path)."""
    return base_argv[:2] + [prompt] + base_argv[2:]


# Any of these grants codex full access (workspace-write blocks network and ``.git``).
_CODEX_WRITE_TOOLS = frozenset({"Edit", "Write", "NotebookEdit"})


def _codex_backend_selected(config: Config) -> bool:
    return str(getattr(config, "ai_backend", "cli") or "cli").lower() == "codex"


def _build_codex_argv(config: Config, allowed_tools: list[str]) -> list[str]:
    codex = getattr(config, "ai_codex", None) or AICodexConfig()
    cmd = [codex.command, "exec", "--json", "--skip-git-repo-check"]
    if _CODEX_WRITE_TOOLS & set(allowed_tools):
        cmd.append("--dangerously-bypass-approvals-and-sandbox")
    else:
        cmd += ["--sandbox", "read-only"]
    if codex.model:
        cmd += ["--model", codex.model]
    if codex.reasoning_effort:
        cmd += ["-c", f'model_reasoning_effort="{codex.reasoning_effort}"']
    cmd += list(codex.extra_args)
    return cmd


def _api_backend_selected(config: Config) -> bool:
    return str(getattr(config, "ai_backend", "cli") or "cli").lower() == "api"


def _build_api_spec(
    config: Config, allowed_tools: list[str] | None = None,
) -> "ApiAgentSpec | None":
    """API-backend spec for this invocation, or ``None`` when another backend is selected."""
    if not _api_backend_selected(config):
        return None

    from releasy.api_agent import DEFAULT_MODEL, ApiAgentSpec

    api = getattr(config, "ai_api", None) or AIApiConfig()
    tools = (
        list(allowed_tools) if allowed_tools is not None
        else list(config.ai_resolve.allowed_tools)
    )
    return ApiAgentSpec(
        model=api.model or config.ai_model or DEFAULT_MODEL,
        effort=config.ai_effort,
        max_tokens=api.max_tokens,
        max_turns=api.max_turns,
        thinking=api.thinking,
        allowed_tools=tools,
        api_key=(os.environ.get(api.api_key_env) or api.api_key or None),
        base_url=api.base_url,
        max_retries=api.max_retries,
        request_timeout_seconds=api.request_timeout_seconds,
        bash_timeout_seconds=api.bash_timeout_seconds,
        tool_output_max_chars=api.tool_output_max_chars,
        system_prompt_extra=api.system_prompt_extra,
    )


def _section_config(
    config: Config, command: str, allowed_tools: list[str], extra_args: list[str],
) -> SimpleNamespace:
    """Config view whose ``ai_resolve`` carries another section's command/tools/args."""
    return SimpleNamespace(
        ai_resolve=SimpleNamespace(
            command=command, allowed_tools=allowed_tools, extra_args=extra_args,
        ),
        ai_model=config.ai_model,
        ai_effort=config.ai_effort,
        ai_backend=config.ai_backend,
        ai_api=config.ai_api,
        ai_codex=config.ai_codex,
    )


def _resolve_backend(
    config: Config, command: str, allowed_tools: list[str] | None = None,
) -> tuple["ApiAgentSpec | None", str | None]:
    """``(api_spec, error)``: spec is None unless the API backend; error says why it can't run."""
    spec = _build_api_spec(config, allowed_tools)
    if spec is not None:
        from releasy.api_agent import check_available
        return spec, check_available(spec)
    if _codex_backend_selected(config):
        command = (getattr(config, "ai_codex", None) or AICodexConfig()).command
    if shutil.which(command) is None:
        return None, f"'{command}' not found on PATH"
    return None, None


def _backend_label(config: Config, command: str) -> str:
    if _codex_backend_selected(config):
        codex = getattr(config, "ai_codex", None) or AICodexConfig()
        return f"{codex.command} ({codex.model})" if codex.model else codex.command
    spec = _build_api_spec(config, allowed_tools=[])
    if spec is None:
        return command
    return f"anthropic api ({spec.resolved_model()})"


def _fmt_elapsed(seconds: float) -> str:
    s = int(seconds)
    if s < 60:
        return f"{s}s"
    if s < 3600:
        return f"{s // 60}m{s % 60:02d}s"
    return f"{s // 3600}h{(s % 3600) // 60:02d}m"


def _flatten(text: str) -> str:
    return text.strip().replace("\n", " ⏎ ")


def _render_event(line: str, start: float) -> str | None:
    """One stream-json event as a console status line, or None if nothing to show."""
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        stripped = line.strip()
        if not stripped:
            return None
        # Stream text often contains ``[…]`` that Rich would parse as markup.
        return f"[dim]│[/dim] {escape(stripped)}"

    elapsed = _fmt_elapsed(time.monotonic() - start)
    etype = ev.get("type")

    if etype == "system":
        sub = ev.get("subtype", "")
        model = ev.get("model") or ""
        if sub == "init":
            return f"[dim]│ [{elapsed}][/dim] [magenta]session start[/magenta] {escape(model)}".rstrip()
        return None

    if etype == "assistant":
        msg = ev.get("message") or {}
        parts = []
        for block in msg.get("content") or []:
            btype = block.get("type")
            if btype == "text":
                txt = _flatten(block.get("text", ""))
                if txt:
                    parts.append(f"[dim]│ [{elapsed}][/dim] [cyan]💬[/cyan] {escape(txt)}")
            elif btype == "thinking":
                txt = _flatten(block.get("thinking", ""))
                if txt:
                    parts.append(f"[dim]│ [{elapsed}] 🧠 {escape(txt)}[/dim]")
            elif btype == "tool_use":
                name = block.get("name", "tool")
                inp = block.get("input") or {}
                summary = ""
                if name == "Bash":
                    summary = _flatten(str(inp.get("command", "")))
                elif name in ("Read", "Write", "Edit"):
                    summary = str(inp.get("file_path") or inp.get("path") or "")
                elif name == "Glob":
                    summary = str(inp.get("pattern") or inp.get("glob_pattern") or "")
                elif name == "Grep":
                    summary = _flatten(str(inp.get("pattern", "")))
                else:
                    keys = ", ".join(list(inp)[:3])
                    summary = f"({keys})" if keys else ""
                line_str = f"[dim]│ [{elapsed}][/dim] [yellow]🔧 {escape(str(name))}[/yellow]"
                if summary:
                    line_str += f" {escape(summary)}"
                parts.append(line_str)
        return "\n".join(parts) if parts else None

    if etype == "user":
        msg = ev.get("message") or {}
        for block in msg.get("content") or []:
            if block.get("type") == "tool_result":
                content = block.get("content")
                if isinstance(content, list):
                    text = " ".join(
                        c.get("text", "") for c in content if isinstance(c, dict)
                    )
                else:
                    text = str(content or "")
                is_err = block.get("is_error")
                marker = "[red]✗[/red]" if is_err else "[green]✓[/green]"
                summary = _flatten(text)
                if not summary:
                    return None
                return f"[dim]│ [{elapsed}][/dim] {marker} [dim]{escape(summary)}[/dim]"
        return None

    if etype == "result":
        sub = ev.get("subtype", "")
        cost = ev.get("total_cost_usd")
        turns = ev.get("num_turns")
        bits = [f"result={escape(sub)}"]
        if turns is not None:
            bits.append(f"turns={turns}")
        if cost is not None:
            bits.append(f"cost=${cost:.3f}")
        return f"[dim]│ [{elapsed}] {' '.join(bits)}[/dim]"

    return None


def _codex_tool_use(name: str, inp: dict) -> dict:
    return {"type": "assistant", "message": {"content": [
        {"type": "tool_use", "name": name, "input": inp},
    ]}}


def _codex_tool_result(text: str, is_error: bool) -> dict:
    return {"type": "user", "message": {"content": [
        {"type": "tool_result", "content": text, "is_error": is_error},
    ]}}


# Informational ``codex exec`` stderr lines, kept out of the transcript.
_CODEX_STDIN_NOTICES = frozenset({
    "Reading prompt from stdin...",
    "Reading additional input from stdin...",
})


def _translate_codex_line(line: str) -> list[str]:
    """``codex exec --json`` event as Claude stream-json lines; other lines pass through."""
    if line.strip() in _CODEX_STDIN_NOTICES:
        return []
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        return [line]
    if not isinstance(ev, dict):
        return [line]
    etype = ev.get("type")
    item = ev.get("item") if isinstance(ev.get("item"), dict) else {}
    itype = item.get("type")
    out: list[dict | str] = []

    if etype == "thread.started":
        out.append({"type": "system", "subtype": "init", "model": "codex"})
    elif etype == "turn.completed":
        out.append({"type": "result", "subtype": "success",
                    "usage": ev.get("usage")})
    elif etype == "turn.failed":
        msg = (ev.get("error") or {}).get("message", "")
        out.append(f"[codex] turn failed: {msg}")
        out.append({"type": "result", "subtype": "error"})
    elif etype == "error":
        out.append(f"[codex] error: {ev.get('message', '')}")
    elif etype == "item.started":
        if itype == "command_execution":
            out.append(_codex_tool_use("Bash", {"command": item.get("command", "")}))
    elif etype == "item.completed":
        if itype == "agent_message":
            out.append({"type": "assistant", "message": {"content": [
                {"type": "text", "text": item.get("text", "")},
            ]}})
        elif itype == "reasoning":
            out.append({"type": "assistant", "message": {"content": [
                {"type": "thinking", "thinking": item.get("text", "")},
            ]}})
        elif itype == "command_execution":
            out.append(_codex_tool_result(
                item.get("aggregated_output", ""), item.get("exit_code") != 0,
            ))
        elif itype == "file_change":
            paths = ", ".join(
                c.get("path", "") for c in item.get("changes") or []
            )
            out.append(_codex_tool_use("Edit", {"file_path": paths}))
            status = item.get("status", "")
            out.append(_codex_tool_result(f"patch {status}", status != "completed"))
        elif itype == "error":
            out.append(f"[codex] {item.get('message', '')}")
        elif itype in ("mcp_tool_call", "web_search", "collab_tool_call"):
            out.append(_codex_tool_use(
                str(itype),
                {k: v for k, v in item.items() if k not in ("id", "type", "status")},
            ))
    elif etype not in ("turn.started", "item.updated"):
        return [line]

    return [
        (json.dumps(o) if isinstance(o, dict) else o) + "\n" for o in out
    ]


def _kill_proc_tree(proc: subprocess.Popen) -> None:
    """SIGTERM (then SIGKILL) ``proc``'s whole process group so its child tools die too."""
    if proc.poll() is not None:
        return
    try:
        pgid = os.getpgid(proc.pid)
    except (ProcessLookupError, OSError):
        return
    try:
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(pgid, signal.SIGKILL)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass


_DEFAULT_EXHAUSTION_MAX_WAIT_SECONDS = 60 * 3600  # 60h
_DEFAULT_EXHAUSTION_POLL_SECONDS = 30 * 60  # 30m


def _exhaustion_kwargs(config: Config) -> dict:
    ai = config.ai_resolve
    return {
        "exhaustion_wait": ai.wait_on_session_exhaustion,
        "exhaustion_max_wait_seconds": ai.session_exhaustion_max_wait_hours * 3600,
        "exhaustion_poll_seconds": ai.session_exhaustion_poll_minutes * 60,
        "exhaustion_extra_patterns": tuple(ai.session_exhaustion_extra_patterns),
    }


def _interruptible_sleep(seconds: float) -> None:
    """Sleep ``seconds`` in small chunks (Ctrl-C responsive, 5-min heartbeat)."""
    end = time.monotonic() + seconds
    next_beat = time.monotonic() + 300.0
    while True:
        remaining = end - time.monotonic()
        if remaining <= 0:
            return
        time.sleep(min(15.0, remaining))
        if time.monotonic() >= next_beat:
            mins_left = int((end - time.monotonic()) / 60) + 1
            console.print(
                f"    [dim]│ …waiting for Claude session (~{mins_left}m "
                "left this poll)[/dim]"
            )
            next_beat += 300.0


def _spawn_claude(
    argv: list[str], repo_path: Path, timeout: int,
    *,
    prompt: str,
    api: "ApiAgentSpec | None" = None,
    exhaustion_wait: bool = True,
    exhaustion_max_wait_seconds: int = _DEFAULT_EXHAUSTION_MAX_WAIT_SECONDS,
    exhaustion_poll_seconds: int = _DEFAULT_EXHAUSTION_POLL_SECONDS,
    exhaustion_extra_patterns: tuple[str, ...] = (),
) -> tuple[int, str, bool]:
    """Run the agent, re-prompting after a sleep while the usage session is exhausted."""
    # A non-positive poll interval would busy-loop.
    wait_enabled = (
        exhaustion_wait
        and exhaustion_poll_seconds > 0
        and exhaustion_max_wait_seconds > 0
    )
    waited = 0.0
    while True:
        if api is not None:
            exit_code, output, timed_out = _run_api_agent_once(
                api, repo_path, timeout, prompt,
            )
        else:
            exit_code, output, timed_out = _spawn_claude_once(
                argv, repo_path, timeout, prompt,
            )
        if not wait_enabled or timed_out or exit_code == 0:
            return exit_code, output, timed_out
        reason = _find_session_exhausted(output, exhaustion_extra_patterns)
        if reason is None:
            return exit_code, output, timed_out
        if waited + exhaustion_poll_seconds > exhaustion_max_wait_seconds:
            console.print(
                f"    [red]✗ Claude session still exhausted after "
                f"{_fmt_elapsed(waited)} of waiting "
                f"(cap {_fmt_elapsed(exhaustion_max_wait_seconds)}); giving up"
                f"[/red] [dim]({reason})[/dim]"
            )
            return exit_code, output, timed_out
        console.print(
            f"    [yellow]⏳ Claude session exhausted[/yellow] "
            f"[dim]({reason})[/dim] — sleeping "
            f"{_fmt_elapsed(exhaustion_poll_seconds)}, then retrying "
            f"[dim](waited {_fmt_elapsed(waited)} / "
            f"{_fmt_elapsed(exhaustion_max_wait_seconds)}; Ctrl-C to abort)[/dim]"
        )
        _interruptible_sleep(exhaustion_poll_seconds)
        waited += exhaustion_poll_seconds


def _run_api_agent_once(
    api: "ApiAgentSpec", repo_path: Path, timeout: int, prompt: str,
) -> tuple[int, str, bool]:
    """API-backend twin of :func:`_spawn_claude_once`."""
    from releasy.api_agent import run_agent

    start = time.monotonic()
    console.print(
        f"    [dim]$ anthropic api {escape(api.resolved_model())}"
        f"{' effort=' + api.effort if api.effort else ''} "
        f"<prompt via messages>[/dim]"
    )
    console.print("    [dim](press Ctrl-C to abort)[/dim]")

    def _render(line: str) -> None:
        rendered = _render_event(line, start)
        if not rendered:
            return
        try:
            console.print(f"    {rendered}")
        except Exception:
            console.print(f"    {rendered}", markup=False, highlight=False)

    return run_agent(api, repo_path, timeout, prompt, _render)


def _spawn_claude_once(
    argv: list[str], repo_path: Path, timeout: int, prompt: str,
) -> tuple[int, str, bool]:
    """Run the CLI agent, streaming to the console. Returns (exit_code, output, timed_out).

    Ctrl-C kills the whole process group and re-raises ``KeyboardInterrupt``.
    """
    use_stdin = len(prompt.encode("utf-8")) > _PROMPT_ARG_MAX_BYTES
    full_argv = argv if use_stdin else _argv_with_inline_prompt(argv, prompt)

    console.print(
        f"    [dim]$ {escape(shlex.join(argv))}"
        f"{' <prompt via stdin>' if use_stdin else ' <prompt…>'}[/dim]"
    )
    console.print("    [dim](press Ctrl-C to abort claude)[/dim]")

    env = os.environ.copy()
    # A backgrounded command dies with the `-p` session, before it reports.
    env["CLAUDE_CODE_DISABLE_BACKGROUND_TASKS"] = "1"

    # Own process group: no terminal Ctrl-C, and the whole tree can be killed at once.
    proc = subprocess.Popen(
        full_argv,
        cwd=repo_path,
        env=env,
        stdin=subprocess.PIPE if use_stdin else subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        start_new_session=True,
    )

    # Feed from a thread so a >pipe-buffer write can't deadlock against stdout reads.
    if use_stdin:
        def _feed() -> None:
            try:
                assert proc.stdin is not None
                proc.stdin.write(prompt)
                proc.stdin.close()
            except (BrokenPipeError, OSError, ValueError):
                pass
        threading.Thread(target=_feed, daemon=True).start()

    collected: list[str] = []
    start = time.monotonic()
    last_output = start
    timed_out = False
    interrupted = False
    stop_heartbeat = threading.Event()

    def _heartbeat() -> None:
        idle_threshold = 30.0
        while not stop_heartbeat.wait(15.0):
            idle = time.monotonic() - last_output
            if idle >= idle_threshold:
                console.print(
                    f"    [dim]│ [{_fmt_elapsed(time.monotonic() - start)}] "
                    f"…still working (idle {int(idle)}s)[/dim]"
                )

    hb = threading.Thread(target=_heartbeat, daemon=True)
    hb.start()

    try:
        assert proc.stdout is not None
        while True:
            if (time.monotonic() - start) > timeout:
                timed_out = True
                break
            try:
                line = proc.stdout.readline()
            except KeyboardInterrupt:
                interrupted = True
                break
            if not line:
                if proc.poll() is not None:
                    break
                continue
            last_output = time.monotonic()
            for out_line in _translate_codex_line(line):
                collected.append(out_line)
                rendered = _render_event(out_line, start)
                if not rendered:
                    continue
                try:
                    console.print(f"    {rendered}")
                except Exception:
                    # A rendering error must not tear down the stream and kill claude.
                    console.print(
                        f"    {rendered}", markup=False, highlight=False,
                    )
    except KeyboardInterrupt:
        interrupted = True
    except Exception as exc:
        collected.append(f"[runner] error streaming claude output: {exc}\n")
    finally:
        stop_heartbeat.set()
        if proc.poll() is None:
            reason = (
                "interrupted by user"
                if interrupted
                else f"timed out after {timeout}s"
                if timed_out
                else "stream ended; cleaning up"
            )
            console.print(
                f"    [yellow]✗ killing claude ({reason})…[/yellow]"
            )
            _kill_proc_tree(proc)

    if interrupted:
        raise KeyboardInterrupt

    exit_code = proc.returncode if proc.returncode is not None else -1
    return exit_code, "".join(collected), timed_out


def _extract_assistant_text(output: str) -> str:
    """All assistant text in a stream-json transcript (raw output if nothing parses)."""
    chunks: list[str] = []
    parsed_any = False
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            chunks.append(line)
            continue
        parsed_any = True
        if ev.get("type") == "assistant":
            for block in (ev.get("message") or {}).get("content") or []:
                if block.get("type") == "text":
                    chunks.append(block.get("text", ""))
        elif ev.get("type") == "result":
            res = ev.get("result")
            if isinstance(res, str):
                chunks.append(res)
    if not parsed_any:
        return output
    return "\n".join(chunks)


# Transient API failures that abort the turn before any work; these are retried.
_TRANSIENT_API_ERROR_RES = [
    re.compile(r"API Error:\s*Stream idle timeout", re.IGNORECASE),
    re.compile(r"API Error:\s*Overloaded", re.IGNORECASE),
    re.compile(r"API Error:\s*5\d\d", re.IGNORECASE),
    re.compile(r"API Error:\s*Connection (?:reset|closed)", re.IGNORECASE),
    re.compile(r"API Error:\s*Request timed out", re.IGNORECASE),
    re.compile(r"API Error:\s*ECONNRESET", re.IGNORECASE),
    re.compile(r"API Error:\s*fetch failed", re.IGNORECASE),
    re.compile(r"partial response received", re.IGNORECASE),
]


def _find_transient_api_error(output: str) -> str | None:
    assistant = _extract_assistant_text(output)
    for haystack in (assistant, output):
        for pat in _TRANSIENT_API_ERROR_RES:
            m = pat.search(haystack)
            if m:
                return m.group(0)
    return None


# Spent usage session (waited out, not retried). The CLI's "monthly spend limit ·
# run /usage-credits" wording is a mislabelled session limit that does reset.
_SESSION_EXHAUSTED_RES = [
    re.compile(r"\blimit reached\b", re.IGNORECASE),
    re.compile(r"reached your (?:usage |5-hour |weekly |daily )?limit", re.IGNORECASE),
    re.compile(r"\bhit your\b[^\n]*?\blimit\b", re.IGNORECASE),
    re.compile(r"\bspend limit\b", re.IGNORECASE),
    re.compile(r"/usage-credits", re.IGNORECASE),
    re.compile(r"\b(?:usage|rate|spend|\d+-hour|weekly|daily|monthly)\s+limit\b", re.IGNORECASE),
    re.compile(r"\blimit (?:will )?reset", re.IGNORECASE),
    re.compile(r"(?:upgrade|ask your admin)[^\n]*(?:higher|increase|raise)[^\n]*limit", re.IGNORECASE),
    re.compile(r"API Error:\s*429", re.IGNORECASE),
]


def _find_session_exhausted(
    output: str, extra_patterns: tuple[str, ...] = (),
) -> str | None:
    """Matched text if the run hit an exhausted usage limit, else None.

    Scans the raw transcript, not model text, to avoid false positives.
    """
    for pat in _SESSION_EXHAUSTED_RES:
        m = pat.search(output)
        if m:
            return m.group(0)
    for raw in extra_patterns:
        try:
            m = re.search(raw, output, re.IGNORECASE)
        except re.error:
            continue
        if m:
            return m.group(0)
    return None


def _extract_cost_usd(output: str) -> float | None:
    """Sum ``total_cost_usd`` over all ``result`` events; None if there is none."""
    total: float | None = None
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            continue
        if ev.get("type") != "result":
            continue
        cost = ev.get("total_cost_usd")
        if isinstance(cost, (int, float)):
            total = (total or 0.0) + float(cost)
    return total


_MISSING_PREREQS_RE = re.compile(
    r"^MISSING_PREREQS:\s*(.+?)\s*$",
    re.MULTILINE,
)
_REASON_RE = re.compile(r"^REASON:\s*(.+?)\s*$", re.MULTILINE)
# Deliberately broad; ``parse_pr_url`` validates downstream.
_PR_URL_TOKEN_RE = re.compile(
    r"https?://github\.com/[^/\s]+/[^/\s]+/pull/\d+[\w/#?=&.\-]*",
    re.IGNORECASE,
)


def _parse_missing_prereqs(output: str) -> tuple[list[str], str | None]:
    """PR URLs from ``MISSING_PREREQS:`` lines and the ``REASON:`` text; ``([], None)`` if none."""
    text = _extract_assistant_text(output)
    urls: list[str] = []
    seen: set[str] = set()
    # Union all occurrences in case Claude restated the line.
    for m in _MISSING_PREREQS_RE.finditer(text):
        for tok in _PR_URL_TOKEN_RE.finditer(m.group(1)):
            url = tok.group(0).rstrip(".,;:)]\"'")
            if url not in seen:
                seen.add(url)
                urls.append(url)
    if not urls:
        return [], None
    reason_match = _REASON_RE.search(text)
    reason = reason_match.group(1).strip() if reason_match else None
    return urls, reason


def _count_iterations(output: str) -> int | None:
    """Best-effort build-attempt count from Claude's narration; None when unknown."""
    text = _extract_assistant_text(output)
    patterns = [
        r"build attempt[s]?:?\s*(\d+)",
        r"iteration\s*(\d+)\s*/\s*\d+",
    ]
    best: int | None = None
    for pat in patterns:
        for m in re.finditer(pat, text, re.IGNORECASE):
            try:
                n = int(m.group(1))
            except ValueError:
                continue
            best = n if best is None else max(best, n)
    return best


# Append-only registry: rows the port adds must be a subset of the source PR's
# own additions. The prompt says so too, but that alone proved unreliable.
_SETTINGS_HISTORY_FILE = "src/Core/SettingsChangesHistory.cpp"

# An added ``{"setting_name", ...`` row.
_SETTINGS_HISTORY_ROW_RE = re.compile(r'^\+\s*\{"([^"]+)"')


def _settings_history_added_names(stdout: str) -> set[str]:
    return {
        m.group(1) for line in stdout.splitlines()
        if (m := _SETTINGS_HISTORY_ROW_RE.match(line))
    }


def _check_settings_history_whitelist(
    repo_path: Path, ctx: AIResolveContext, new_head: str,
) -> tuple[bool, str | None]:
    """Check the port's SettingsChangesHistory.cpp additions ⊆ the source PR's additions."""
    source_sha = ctx.source_pr.merge_commit_sha or ctx.source_pr.head_sha
    if not source_sha or not ctx.start_sha:
        return True, None

    on_port = run_git(
        ["diff", "--no-color", f"{ctx.start_sha}..{new_head}",
         "--", _SETTINGS_HISTORY_FILE],
        repo_path, check=False,
    )
    if on_port.returncode != 0 or not on_port.stdout.strip():
        return True, None  # file untouched by the port

    added_on_port = _settings_history_added_names(on_port.stdout)
    if not added_on_port:
        return True, None

    # Same diff the prompt tells Claude to read.
    src = run_git(
        ["show", "-m", "--first-parent", "--no-color", source_sha,
         "--", _SETTINGS_HISTORY_FILE],
        repo_path, check=False,
    )
    allowed = (
        _settings_history_added_names(src.stdout) if src.returncode == 0
        else set()
    )

    extra = added_on_port - allowed
    if not extra:
        return True, None

    sample = ", ".join(sorted(extra)[:5])
    more = f" (+{len(extra) - 5} more)" if len(extra) > 5 else ""
    return False, (
        f"{_SETTINGS_HISTORY_FILE}: {len(extra)} unauthorized setting "
        f"row(s) added during resolution: {sample}{more} — these names "
        "are not in the source PR's diff for this file. This registry "
        "is append-only: only rows the source PR itself adds may land "
        "in the port. Re-resolve and drop the extras (likely context "
        "lines from \"ours\" that got swept in alongside a real edit)."
    )


# ``err_kind``s handed back to Claude for an in-place correction.
_CORRECTABLE_POSTCONDITIONS = {"settings_history"}

# ``err_kind``s that keep the resolution (flagged on the PR) once corrections
# run out, when ``ai_resolve.warn_on_unfixed_postconditions`` is on.
_DOWNGRADABLE_POSTCONDITIONS = {"settings_history"}


def flatten_resolve_warnings(warnings: list[str]) -> list[str]:
    """One single-line entry per non-empty warning."""
    return [" ".join(w.split()) for w in warnings if w and w.strip()]


def resolve_warning_comment_body(warnings: list[str]) -> str:
    lines = [
        "## RelEasy — resolution kept with warnings",
        "",
        "The AI resolution was pushed, but a post-resolution check is "
        "still failing on it. **Nothing was rolled back** — please review "
        "the point(s) below before merging and either fix them or dismiss "
        "them as false positives.",
        "",
    ]
    lines += [f"- {line}" for line in flatten_resolve_warnings(warnings)]
    return "\n".join(lines).rstrip() + "\n"


def flag_resolution_warnings_on_pr(
    config: Config, pr_url: str | None, warnings: list[str],
) -> bool:
    """Comment on and ``verify_label`` a PR kept with warnings; True iff the comment landed."""
    if not warnings or not pr_url:
        return False
    parsed = parse_pr_url(pr_url)
    if parsed is None:
        console.print(
            f"    [yellow]![/yellow] could not parse PR URL for the "
            f"resolution-warning comment: {pr_url!r}"
        )
        return False
    owner, repo, number = parsed

    # The comment/label helpers address origin by PR number.
    origin_slug = get_origin_repo_slug(config)
    if origin_slug and f"{owner}/{repo}".lower() != origin_slug.lower():
        console.print(
            f"    [yellow]![/yellow] {pr_url} is not on origin "
            f"({origin_slug}) — not commenting the resolution warning there"
        )
        return False

    posted = add_issue_comment(
        config, number, resolve_warning_comment_body(warnings),
    )
    if posted:
        console.print(
            f"    [yellow]💬[/yellow] Flagged the kept resolution on "
            f"[link={pr_url}]PR #{number}[/link]"
        )
    else:
        console.print(
            f"    [yellow]![/yellow] could not comment the resolution "
            f"warning on PR #{number} — it is only in this log"
        )
    add_label_to_pr(config, number, config.ai_resolve.verify_label)
    return posted


# Literal ``{"..."}`` rows survive placeholder filling: ``"`` is not an identifier char.
_SETTINGS_HISTORY_FIX_PROMPT = """\
You are fixing ONE specific problem in an ALREADY-COMPLETED cherry-pick. Do not start over.

## State
- Repo: {cwd}
- Port branch `{port_branch}` is checked out; the working tree is clean.
- The cherry-pick of {source_pr_url} is ALREADY resolved and committed at HEAD.
  Do NOT run `git cherry-pick`, `git reset`, `git rebase`, `git merge`, or check out any other ref.
- Source PR merge/commit SHA: `{source_pr_merge_sha}`
- Port base (HEAD before the pick): `{start_sha}`

## Problem
RelEasy's post-resolution check rejected the landed resolution:

> {err}

`src/Core/SettingsChangesHistory.cpp` is an APPEND-ONLY registry. The rows your
port ADDS to this file must be a SUBSET of the rows the SOURCE PR's own diff
adds. The flagged rows above are almost always context / "ours" lines that got
swept in alongside a real edit — they are NOT part of this port.

## Fix
1. List the rows the SOURCE PR legitimately adds to this file:
   ```
   git show -m --first-parent --no-color {source_pr_merge_sha} -- src/Core/SettingsChangesHistory.cpp
   ```
2. List the rows your port currently adds:
   ```
   git diff --no-color {start_sha}..HEAD -- src/Core/SettingsChangesHistory.cpp
   ```
3. Edit `src/Core/SettingsChangesHistory.cpp` and DELETE every added
   {"setting_name", ...} row whose setting name is NOT in the source PR's
   additions from step 1. Keep the legitimately-added rows exactly where they
   belong (in the correct version block). Change NOTHING else; touch NO other file.
4. Keep the file valid C++ (balanced braces, no dangling/missing commas in the
   initializer). A full rebuild is NOT required for this registry-only edit.
5. Fold the fix into the existing resolution commit — do not create a new one:
   ```
   git add -- src/Core/SettingsChangesHistory.cpp
   git commit --amend --no-edit
   ```

When done, print `DONE`. If the complaint is genuinely wrong (every flagged row
really is in the source PR's diff from step 1), print `DONE` without editing and
RelEasy will re-verify.
"""


def _render_correction_prompt(
    config: Config, repo_path: Path, ctx: AIResolveContext,
    err_kind: str, err: str | None,
) -> str:
    """Follow-up prompt for a correctable postcondition; ``ValueError`` if there is none."""
    if err_kind != "settings_history":
        raise ValueError(f"no correction prompt for postcondition {err_kind!r}")

    source_sha = (
        ctx.source_pr.merge_commit_sha or ctx.source_pr.head_sha or ""
    )
    placeholders = {
        "cwd": str(repo_path),
        "port_branch": ctx.port_branch,
        "source_pr_url": ctx.source_pr.url,
        "source_pr_merge_sha": source_sha,
        "start_sha": ctx.start_sha or "",
        "err": (err or "").strip(),
    }
    return _fill_placeholders(_SETTINGS_HISTORY_FIX_PROMPT, placeholders)


def _verify_postconditions(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> tuple[bool, str | None, str | None, str | None]:
    """Check the operation concluded, nothing is unmerged, HEAD advanced and the registry is clean.

    Returns ``(ok, new_head, error, err_kind)``; ``err_kind`` is set only for
    :data:`_CORRECTABLE_POSTCONDITIONS`.
    """
    if is_operation_in_progress(repo_path):
        return False, None, (
            "cherry-pick/merge/rebase still in progress after claude exited"
        ), None

    # Only unmerged paths count; other dirt is build/runtime noise.
    porc = run_git(
        ["status", "--porcelain", "--untracked-files=no"],
        repo_path, check=False,
    )
    unmerged = [
        line for line in porc.stdout.splitlines()
        if len(line) >= 2 and (
            line[0] == "U" or line[1] == "U"
            or line[:2] in {"AA", "DD"}
        )
    ]
    if unmerged:
        files = ", ".join(line[3:] for line in unmerged[:5])
        return False, None, f"unmerged paths after claude: {files}", None

    head = run_git(["rev-parse", "--verify", "HEAD"], repo_path, check=False)
    if head.returncode != 0:
        return False, None, "could not read HEAD", None
    new_head = head.stdout.strip()

    if ctx.start_sha and new_head == ctx.start_sha:
        return False, new_head, (
            "no new commits — cherry-pick was not concluded"
        ), None

    if ctx.split_mode and ctx.pre_resolve_sha and new_head == ctx.pre_resolve_sha:
        return False, new_head, (
            "no resolution commit on top of the 'with conflicts' commit "
            "— claude did not produce a second commit"
        ), None

    ok, sh_err = _check_settings_history_whitelist(repo_path, ctx, new_head)
    if not ok:
        return False, new_head, sh_err, "settings_history"

    return True, new_head, None, None


def _invoke_claude_with_retries(
    config: Config, repo_path: Path, prompt: str,
    *, timeout: int | None = None, allowed_tools: list[str] | None = None,
) -> tuple[int, str, bool, float | None]:
    """Run claude on ``prompt``, retrying transient API errors.

    Returns the final attempt's ``(exit_code, output, timed_out)`` plus the
    cost summed across attempts.
    """
    spawn_timeout = (
        timeout if timeout is not None else config.ai_resolve.timeout_seconds
    )
    argv = _build_claude_argv(config, allowed_tools)
    api = _build_api_spec(config, allowed_tools)
    max_attempts = max(1, config.ai_resolve.api_retries + 1)
    backoff = max(0, config.ai_resolve.api_retry_backoff_seconds)

    last_exit_code = -1
    last_output = ""
    last_timed_out = False
    cost_usd_total: float | None = None

    for attempt in range(1, max_attempts + 1):
        if attempt > 1:
            console.print(
                f"    [yellow]↻ retrying claude after transient API error "
                f"(attempt {attempt}/{max_attempts}, sleeping {backoff}s)"
                f"[/yellow]"
            )
            time.sleep(backoff)

        exit_code, output, timed_out = _spawn_claude(
            argv, repo_path, spawn_timeout, prompt=prompt, api=api,
            **_exhaustion_kwargs(config),
        )
        last_exit_code, last_output, last_timed_out = exit_code, output, timed_out

        attempt_cost = _extract_cost_usd(output)
        if attempt_cost is not None:
            cost_usd_total = (cost_usd_total or 0.0) + attempt_cost

        if timed_out:
            break

        transient = _find_transient_api_error(output)
        if transient and exit_code != 0 and attempt < max_attempts:
            console.print(
                f"    [yellow]⚠ transient API error: {transient}"
                f" — will retry[/yellow]"
            )
            continue

        break

    return last_exit_code, last_output, last_timed_out, cost_usd_total


def resolve_with_claude(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> AIResolveResult:
    """Render the prompt, run claude, and verify post-conditions."""
    _api, backend_error = _resolve_backend(config, config.ai_resolve.command)
    if backend_error:
        return AIResolveResult(
            success=False, error=backend_error, api_aborted=True,
        )

    # In resolve-only mode build_verify writes the build wrapper.
    if not ctx.skip_build:
        try:
            _write_build_script(
                repo_path, config.ai_resolve.build_command,
                build_log_path(ctx.port_branch),
            )
        except OSError as exc:
            return AIResolveResult(
                success=False, error=f"could not write build wrapper: {exc}",
                api_aborted=True,
            )

    try:
        prompt = _render_prompt(config, repo_path, ctx)
    except FileNotFoundError as exc:
        return AIResolveResult(success=False, error=str(exc), api_aborted=True)

    build_note = (
        "resolve only, no build" if ctx.skip_build
        else f"max {config.ai_resolve.max_iterations} build attempts"
    )
    console.print(
        f"    [magenta]\U0001f916 invoking "
        f"{_backend_label(config, config.ai_resolve.command)} "
        f"(timeout {config.ai_resolve.timeout_seconds}s, {build_note}, "
        f"up to {config.ai_resolve.api_retries} API-error retries)[/magenta]"
    )

    max_attempts = max(1, config.ai_resolve.api_retries + 1)
    exit_code, output, timed_out, cost_usd_total = _invoke_claude_with_retries(
        config, repo_path, prompt,
    )

    iterations = _count_iterations(output)
    assistant_text = _extract_assistant_text(output)

    if timed_out:
        return AIResolveResult(
            success=False, timed_out=True, iterations=iterations,
            error=f"claude timed out after {config.ai_resolve.timeout_seconds}s",
            cost_usd=cost_usd_total,
        )

    tail_lines = assistant_text.strip().splitlines()[-40:] if assistant_text.strip() else []
    tail_str = "\n".join(tail_lines)

    # Before UNRESOLVED (it is printed with MISSING_PREREQS too); full transcript,
    # since the marker can come mid-narration.
    missing_prereq_prs, missing_prereq_note = _parse_missing_prereqs(output)
    if missing_prereq_prs:
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported MISSING_PREREQS",
            cost_usd=cost_usd_total,
            missing_prereq_prs=missing_prereq_prs,
            missing_prereq_note=missing_prereq_note,
        )
    if any(line.strip() == "UNRESOLVED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported UNRESOLVED",
            cost_usd=cost_usd_total,
        )
    if any(line.strip() == "BUILD FAILED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported BUILD FAILED",
            cost_usd=cost_usd_total,
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = (
            f" (transient API error after {max_attempts} attempt(s): {transient})"
            if transient
            else ""
        )
        no_billed_work = not iterations and not cost_usd_total
        return AIResolveResult(
            success=False, iterations=iterations,
            error=f"claude exited with code {exit_code}{suffix}\n{tail_str}",
            cost_usd=cost_usd_total,
            api_aborted=bool(transient) or no_billed_work,
        )

    ok, new_head, err, err_kind = _verify_postconditions(config, repo_path, ctx)

    # Hand a correctable failure back to Claude to amend the committed resolution in place.
    fix_passes = max(0, config.ai_resolve.postcondition_retries)
    pass_no = 0
    # Set when a correction pass died mid-flight (timeout / dropped turn).
    bail_note: str | None = None
    bail_timed_out = False
    while (
        not ok
        and err_kind in _CORRECTABLE_POSTCONDITIONS
        and pass_no < fix_passes
    ):
        try:
            fix_prompt = _render_correction_prompt(
                config, repo_path, ctx, err_kind, err,
            )
        except ValueError:
            break

        pass_no += 1
        console.print(
            f"    [yellow]↻ postcondition '{err_kind}' failed — asking "
            f"{_backend_label(config, config.ai_resolve.command)} "
            "to correct it in place "
            f"(pass {pass_no}/{fix_passes})[/yellow]"
        )

        fc, fout, fto, fcost = _invoke_claude_with_retries(
            config, repo_path, fix_prompt,
        )
        if fcost is not None:
            cost_usd_total = (cost_usd_total or 0.0) + fcost
        if fto:
            bail_note = (
                f"claude timed out after {config.ai_resolve.timeout_seconds}s "
                f"correcting postcondition '{err_kind}' (pass {pass_no})"
            )
            bail_timed_out = True
            break
        # A transient error dropped the turn: bail. Other non-zero exits still
        # re-verify, since the fix may have landed before a late failure.
        if fc != 0:
            transient = _find_transient_api_error(fout)
            if transient:
                bail_note = (
                    f"transient API error correcting postcondition "
                    f"'{err_kind}' (pass {pass_no}): {transient}"
                )
                break
        ok, new_head, err, err_kind = _verify_postconditions(
            config, repo_path, ctx,
        )

    if bail_note:
        # A pass that died late may still have landed its amend.
        ok, new_head, err, err_kind = _verify_postconditions(
            config, repo_path, ctx,
        )
        if not ok:
            err = f"{err}\n({bail_note})"
    elif not ok and pass_no:
        err = f"{err}\n(still failing after {pass_no} correction pass(es))"

    if not ok:
        keep = (
            err_kind in _DOWNGRADABLE_POSTCONDITIONS
            and config.ai_resolve.warn_on_unfixed_postconditions
        )
        if not keep:
            return AIResolveResult(
                success=False, iterations=iterations, new_head=new_head,
                error=err, timed_out=bail_timed_out,
                cost_usd=cost_usd_total,
            )
        console.print(
            f"    [yellow]⚠ postcondition '{err_kind}' is still failing — "
            "keeping the resolution anyway; it is flagged for review on "
            "the PR[/yellow]"
        )
        for line in (err or "").strip().splitlines():
            console.print(f"      [dim]{escape(line)}[/dim]")
        return AIResolveResult(
            success=True, iterations=iterations, new_head=new_head,
            cost_usd=cost_usd_total, warnings=[err or err_kind],
        )

    return AIResolveResult(
        success=True, iterations=iterations, new_head=new_head, error=err,
        cost_usd=cost_usd_total,
    )


@dataclass
class AITextResult:
    success: bool
    text: str | None = None
    error: str | None = None
    timed_out: bool = False
    cost_usd: float | None = None


def synthesize_text(
    config: Config,
    prompt: str,
    *,
    label: str,
    timeout_seconds: int,
    command: str,
) -> AITextResult:
    """Run Claude on ``prompt`` with no tools, in a throwaway cwd, and return its reply text."""
    api, backend_error = _resolve_backend(config, command, allowed_tools=[])
    if backend_error:
        return AITextResult(success=False, error=backend_error)

    if _codex_backend_selected(config):
        argv = _build_codex_argv(config, [])
    else:
        argv = [
            command,
            "-p",
            "--output-format", "stream-json",
            "--verbose",
            "--allowedTools", "",
        ]
        argv += _model_effort_args(config)

    console.print(
        f"    [magenta]\U0001f916 synthesizing text via "
        f"{_backend_label(config, command)} for [cyan]{label}[/cyan] "
        f"(timeout {timeout_seconds}s)[/magenta]"
    )

    import tempfile

    with tempfile.TemporaryDirectory(prefix="releasy-ai-text-") as td:
        exit_code, output, timed_out = _spawn_claude(
            argv, Path(td), timeout_seconds, prompt=prompt, api=api,
            **_exhaustion_kwargs(config),
        )

    cost = _extract_cost_usd(output)

    if timed_out:
        return AITextResult(
            success=False, timed_out=True, cost_usd=cost,
            error=f"claude timed out after {timeout_seconds}s",
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = f" ({transient})" if transient else ""
        return AITextResult(
            success=False, cost_usd=cost,
            error=f"claude exited with code {exit_code}{suffix}",
        )

    text = _extract_assistant_text(output).strip()
    if not text:
        return AITextResult(
            success=False, cost_usd=cost,
            error="claude returned empty output",
        )

    return AITextResult(success=True, text=text, cost_usd=cost)


def synthesize_changelog_entry(
    config: Config,
    *,
    unit_label: str,
    pr_blocks: str,
    n_prs: int,
    base_branch: str,
    source_repo: str,
) -> AITextResult:
    """Render the changelog-synthesis prompt around caller-built ``pr_blocks`` and run it."""
    prompt_path = _prompt_path(config, config.ai_changelog.prompt_file)
    if not prompt_path.exists():
        return AITextResult(
            success=False,
            error=(
                "changelog-synthesis prompt template not found: "
                f"{prompt_path}. Set ai_changelog.prompt_file in config "
                "to point at a real file."
            ),
        )

    template = prompt_path.read_text(encoding="utf-8")
    placeholders = {
        "n_prs": str(n_prs),
        "base_branch": base_branch,
        "source_repo": source_repo,
        "pr_blocks": pr_blocks,
    }
    rendered = _fill_placeholders(template, placeholders)

    return synthesize_text(
        config, rendered,
        label=unit_label,
        timeout_seconds=config.ai_changelog.timeout_seconds,
        command=config.ai_changelog.command,
    )


def attempt_ai_resolve(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> AIResolveResult:
    """:func:`resolve_with_claude`; on failure abort the git operation and reset to ``start_sha``.

    ``ctx.start_sha`` defaults to the current HEAD.
    """
    if ctx.start_sha is None:
        head = run_git(["rev-parse", "--verify", "HEAD"], repo_path, check=False)
        ctx.start_sha = head.stdout.strip() if head.returncode == 0 else None

    result = resolve_with_claude(config, repo_path, ctx)

    if result.success:
        return result

    if is_operation_in_progress(repo_path):
        run_git(["cherry-pick", "--abort"], repo_path, check=False)
        run_git(["merge", "--abort"], repo_path, check=False)
        run_git(["rebase", "--abort"], repo_path, check=False)
    if ctx.start_sha:
        run_git(["reset", "--hard", ctx.start_sha], repo_path, check=False)

    return result


# Advisory read-only verifier pass over the landed resolution.
_VERIFY_ALLOWED_TOOLS = (
    "Read", "Glob", "Grep",
    "Bash(git:*)", "Bash(gh:*)",
    "Bash(ls:*)", "Bash(cat:*)", "Bash(head:*)", "Bash(tail:*)",
    "Bash(rg:*)", "Bash(wc:*)",
)


VerifyVerdict = Literal["ok", "needs_attention", "unknown"]


@dataclass
class VerifyContext:
    port_branch: str
    base_branch: str
    source_pr: PRInfo
    start_sha: str
    new_head: str
    conflict_files: list[str] = field(default_factory=list)
    user_context: str = ""
    mode: PortMode = "forward_port"


@dataclass
class VerifyResult:
    # True iff the verifier ran cleanly, whatever the verdict.
    success: bool
    verdict: VerifyVerdict = "unknown"
    summary: str = ""
    findings: list[str] = field(default_factory=list)
    error: str | None = None
    timed_out: bool = False
    cost_usd: float | None = None


def _render_verify_prompt(config: Config, repo_path: Path, ctx: VerifyContext) -> str:
    prompt_path = _prompt_path(config, config.ai_resolve.verify_prompt_file)
    if not prompt_path.exists():
        raise FileNotFoundError(
            f"Verifier prompt template not found: {prompt_path}. "
            "Set ai_resolve.verify_prompt_file in config."
        )

    template = prompt_path.read_text(encoding="utf-8")

    repo_slug = get_origin_repo_slug(config) or "<unknown>"

    conflict_files_md = "\n".join(f"- `{f}`" for f in ctx.conflict_files) or "- (none)"

    body = (ctx.source_pr.body or "").strip()
    if not body:
        body = "_(empty)_"
    elif len(body) > 4000:
        body = body[:4000] + "\n\n_(truncated)_"

    source_pr_merge_sha = (
        ctx.source_pr.merge_commit_sha or ctx.source_pr.head_sha or ""
    )

    user_context_text = (ctx.user_context or "").strip()
    if user_context_text:
        user_context_section = (
            "\n## User-supplied context (from session.yaml)\n\n"
            "> The operator attached this note to this PR / group when "
            "configuring the run. Treat it as a hint about the resolver's "
            "intent, not a license to relax the in-scope rule.\n\n"
            f"{user_context_text}\n"
        )
    else:
        user_context_section = ""

    placeholders = {
        "repo_slug": repo_slug,
        "cwd": str(repo_path),
        "port_branch": ctx.port_branch,
        "base_branch": ctx.base_branch,
        "source_pr_url": ctx.source_pr.url,
        "source_pr_title": ctx.source_pr.title,
        "source_pr_number": str(ctx.source_pr.number),
        "source_pr_body": body,
        "source_pr_merge_sha": source_pr_merge_sha,
        "start_sha": ctx.start_sha,
        "new_head": ctx.new_head,
        "conflict_files": conflict_files_md,
        "user_context_section": user_context_section,
        "port_direction": ctx.mode,
        "source_pr_labels": ", ".join(
            l for l in (ctx.source_pr.labels or []) if l
        ),
    }

    return _fill_placeholders(template, placeholders)


_VERIFY_VERDICT_RE = re.compile(
    r"^\s*VERDICT\s*:\s*(OK|NEEDS_ATTENTION)\s*$",
    re.IGNORECASE | re.MULTILINE,
)
_VERIFY_SUMMARY_RE = re.compile(
    r"^\s*SUMMARY\s*:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE,
)
_VERIFY_END_RE = re.compile(r"^\s*END_VERIFY\s*$", re.IGNORECASE | re.MULTILINE)


def _parse_verify_output(output: str) -> tuple[VerifyVerdict, str, list[str]]:
    """Parse VERDICT / SUMMARY / FINDINGS; verdict is ``"unknown"`` when malformed."""
    text = _extract_assistant_text(output)

    verdict: VerifyVerdict = "unknown"
    verdict_matches = list(_VERIFY_VERDICT_RE.finditer(text))
    if verdict_matches:
        raw = verdict_matches[-1].group(1).strip().upper()
        if raw == "OK":
            verdict = "ok"
        elif raw == "NEEDS_ATTENTION":
            verdict = "needs_attention"

    summary = ""
    summary_matches = list(_VERIFY_SUMMARY_RE.finditer(text))
    if summary_matches:
        summary = summary_matches[-1].group(1).strip()

    findings: list[str] = []
    # Scan the last FINDINGS: block before END_VERIFY (or EOF).
    findings_block = ""
    findings_idx = text.lower().rfind("findings:")
    if findings_idx >= 0:
        tail = text[findings_idx + len("findings:"):]
        end_match = _VERIFY_END_RE.search(tail)
        findings_block = tail[: end_match.start()] if end_match else tail
    for line in findings_block.splitlines():
        line = line.strip()
        if not line:
            continue
        for prefix in ("- ", "* ", "• "):
            if line.startswith(prefix):
                line = line[len(prefix):].strip()
                break
        else:
            m = re.match(r"^\d+\.\s+(.+)$", line)
            if m:
                line = m.group(1).strip()
            else:
                # First non-bullet line ends the block.
                break
        if not line or line.lower() == "(none)":
            continue
        findings.append(line)

    return verdict, summary, findings


def verify_ai_resolution(
    config: Config, repo_path: Path, ctx: VerifyContext,
) -> VerifyResult:
    """Run the advisory verifier; never mutates the repo or remote."""
    api, backend_error = _resolve_backend(
        config, config.ai_resolve.command, list(_VERIFY_ALLOWED_TOOLS),
    )
    if backend_error:
        return VerifyResult(success=False, error=backend_error)

    try:
        prompt = _render_verify_prompt(config, repo_path, ctx)
    except FileNotFoundError as exc:
        return VerifyResult(success=False, error=str(exc))

    argv = _build_claude_argv(config, list(_VERIFY_ALLOWED_TOOLS))

    console.print(
        "    [magenta]\U0001f50e verifying AI resolution "
        f"(timeout {config.ai_resolve.verify_timeout_seconds}s, read-only)[/magenta]"
    )

    exit_code, output, timed_out = _spawn_claude(
        argv, repo_path, config.ai_resolve.verify_timeout_seconds,
        prompt=prompt, api=api, **_exhaustion_kwargs(config),
    )

    cost = _extract_cost_usd(output)

    if timed_out:
        return VerifyResult(
            success=False, timed_out=True, cost_usd=cost,
            error=f"verifier timed out after {config.ai_resolve.verify_timeout_seconds}s",
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = f" ({transient})" if transient else ""
        return VerifyResult(
            success=False, cost_usd=cost,
            error=f"verifier exited with code {exit_code}{suffix}",
        )

    verdict, summary, findings = _parse_verify_output(output)
    if verdict == "unknown":
        return VerifyResult(
            success=False, cost_usd=cost, verdict=verdict,
            summary=summary, findings=findings,
            error="verifier did not emit a parsable VERDICT line",
        )

    return VerifyResult(
        success=True, verdict=verdict, summary=summary,
        findings=findings, cost_usd=cost,
    )
